name: Mockup Front Deployment
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      STAGE: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: yeongroyun/ku-hackathon-frontend:${{ env.STAGE }}
